/**
 * SI-AKTIF Calendar Feature
 */

window.Calendar = {
    currentDate: new Date(),
    selectedDate: new Date(),
    teacherId: null, // If admin, this holds the selected teacher
    
    dailyData: [],
    mapelData: [],
    allClasses: [],

    renderCalendar: async (user) => {
        const container = document.getElementById('page-calendar');
        
        let html = `
            <div class="calendar-header-actions">
                <h2 class="font-heading">Kalender Absensi</h2>
                ${user.role === 'admin' ? `
                    <div style="display: flex; gap: 1rem; align-items: center;">
                        <label style="font-size: 0.875rem; color: var(--color-text-light);">Lihat Absensi Guru:</label>
                        <select id="calendar-teacher-select" class="form-control" style="width: 250px;">
                            <option value="">-- Pilih Guru --</option>
                        </select>
                    </div>
                ` : ''}
            </div>

            <div class="calendar-layout">
                <div class="calendar-main">
                    <div class="calendar-month-nav" style="width: fit-content; margin-bottom: 1rem;">
                        <button onclick="window.Calendar.changeMonth(-1)"><i data-lucide="chevron-left"></i></button>
                        <span id="calendar-month-year">June 2026</span>
                        <button onclick="window.Calendar.changeMonth(1)"><i data-lucide="chevron-right"></i></button>
                    </div>

                    <div class="calendar-grid">
                        <div class="calendar-day-header">Sun</div>
                        <div class="calendar-day-header">Mon</div>
                        <div class="calendar-day-header">Tue</div>
                        <div class="calendar-day-header">Wed</div>
                        <div class="calendar-day-header">Thu</div>
                        <div class="calendar-day-header">Fri</div>
                        <div class="calendar-day-header">Sat</div>
                    </div>
                    <div class="calendar-grid" id="calendar-days-container">
                        <!-- Days generated by JS -->
                    </div>
                </div>

                <div class="calendar-details-panel">
                    <div class="calendar-details-header">
                        <i data-lucide="calendar" style="color: var(--color-emerald);"></i>
                        <h3 id="calendar-selected-date-title">Senin, 1 Juni 2026</h3>
                    </div>
                    <div class="calendar-details-subtitle" id="calendar-selected-events-count">0 EVENTS LOGGED</div>
                    
                    <div id="calendar-events-list">
                        <!-- Events generated by JS -->
                    </div>
                </div>
            </div>
        `;
        
        container.innerHTML = html;
        if (window.lucide) lucide.createIcons({ root: container });

        // Load data
        window.Calendar.allClasses = await window.DB.getClasses();
        window.Calendar.dailyData = await window.DB.getAttendanceDaily();
        window.Calendar.mapelData = await window.DB.getAttendanceSubject();

        if (user.role === 'admin') {
            const users = await window.DB.getUsers();
            const teachers = users.filter(u => u.role === 'teacher');
            const select = document.getElementById('calendar-teacher-select');
            teachers.forEach(t => {
                const opt = document.createElement('option');
                opt.value = t.id;
                opt.textContent = t.name;
                select.appendChild(opt);
            });
            select.addEventListener('change', (e) => {
                window.Calendar.teacherId = e.target.value;
                window.Calendar.drawGrid();
                window.Calendar.drawDetails();
            });
        } else {
            window.Calendar.teacherId = user.id;
        }

        window.Calendar.currentDate = new Date();
        window.Calendar.selectedDate = new Date();
        
        window.Calendar.drawGrid();
        window.Calendar.drawDetails();
    },

    changeMonth: (delta) => {
        window.Calendar.currentDate.setMonth(window.Calendar.currentDate.getMonth() + delta);
        window.Calendar.drawGrid();
    },

    drawGrid: () => {
        const year = window.Calendar.currentDate.getFullYear();
        const month = window.Calendar.currentDate.getMonth();
        
        const monthNames = ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];
        document.getElementById('calendar-month-year').textContent = `${monthNames[month]} ${year}`;

        const firstDay = new Date(year, month, 1).getDay(); // 0 = Sun
        const daysInMonth = new Date(year, month + 1, 0).getDate();
        const daysInPrevMonth = new Date(year, month, 0).getDate();

        const container = document.getElementById('calendar-days-container');
        container.innerHTML = '';

        // Get events for the selected teacher to draw dots
        const teacherId = window.Calendar.teacherId;
        
        // Draw previous month filler days
        for (let i = 0; i < firstDay; i++) {
            const dayNum = daysInPrevMonth - firstDay + i + 1;
            container.appendChild(window.Calendar.createDayCell(dayNum, true));
        }

        // Draw current month days
        for (let i = 1; i <= daysInMonth; i++) {
            const cellDate = new Date(year, month, i);
            const dateString = cellDate.toISOString().split('T')[0];
            
            // Check events
            let hasDaily = false;
            let hasMapel = false;

            if (teacherId) {
                hasDaily = window.Calendar.dailyData.some(d => d.date === dateString && d.waliKelasId === teacherId);
                hasMapel = window.Calendar.mapelData.some(d => d.date === dateString && d.teacherId === teacherId);
            }

            const cell = window.Calendar.createDayCell(i, false, cellDate, hasDaily, hasMapel);
            container.appendChild(cell);
        }

        // Fill remaining days
        const totalCells = firstDay + daysInMonth;
        const remainingCells = 42 - totalCells; // 6 rows * 7
        for (let i = 1; i <= remainingCells; i++) {
            container.appendChild(window.Calendar.createDayCell(i, true));
        }
    },

    createDayCell: (dayNumber, isOtherMonth, dateObj = null, hasDaily = false, hasMapel = false) => {
        const div = document.createElement('div');
        div.className = 'calendar-day';
        if (isOtherMonth) div.classList.add('other-month');

        const numDiv = document.createElement('div');
        numDiv.className = 'calendar-day-number';
        numDiv.textContent = dayNumber;
        div.appendChild(numDiv);

        if (!isOtherMonth) {
            // Check if selected
            if (dateObj.toDateString() === window.Calendar.selectedDate.toDateString()) {
                div.classList.add('active');
            }

            // Add indicators
            if (hasDaily || hasMapel) {
                const indDiv = document.createElement('div');
                indDiv.className = 'calendar-day-indicators';
                if (hasDaily) {
                    const dot = document.createElement('div');
                    dot.className = 'calendar-dot hadir'; // green dot
                    indDiv.appendChild(dot);
                }
                if (hasMapel) {
                    const dot = document.createElement('div');
                    dot.className = 'calendar-dot izin'; // blue dot
                    indDiv.appendChild(dot);
                }
                div.appendChild(indDiv);
            }

            div.addEventListener('click', () => {
                window.Calendar.selectedDate = dateObj;
                window.Calendar.drawGrid(); // re-render to update active state
                window.Calendar.drawDetails();
            });
        }

        return div;
    },

    drawDetails: () => {
        const titleEl = document.getElementById('calendar-selected-date-title');
        const countEl = document.getElementById('calendar-selected-events-count');
        const listEl = document.getElementById('calendar-events-list');

        const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' };
        titleEl.textContent = window.Calendar.selectedDate.toLocaleDateString('id-ID', options);

        listEl.innerHTML = '';

        if (!window.Calendar.teacherId) {
            countEl.textContent = 'PILIH GURU TERLEBIH DAHULU';
            listEl.innerHTML = '<p style="color: var(--color-text-light); font-size: 0.875rem;">Silakan pilih nama guru pada dropdown di atas untuk melihat riwayat absensi.</p>';
            return;
        }

        const dateString = window.Calendar.selectedDate.toISOString().split('T')[0];
        const teacherId = window.Calendar.teacherId;

        // Find events
        const dailyEvents = window.Calendar.dailyData.filter(d => d.date === dateString && d.waliKelasId === teacherId);
        const mapelEvents = window.Calendar.mapelData.filter(d => d.date === dateString && d.teacherId === teacherId);

        let totalEvents = dailyEvents.length + mapelEvents.length;
        countEl.textContent = `${totalEvents} EVENT(S) LOGGED`;

        if (totalEvents === 0) {
            listEl.innerHTML = '<p style="color: var(--color-text-light); font-size: 0.875rem;">Tidak ada catatan absensi pada tanggal ini.</p>';
            return;
        }

        // Render Daily
        dailyEvents.forEach(ev => {
            const classObj = window.Calendar.allClasses.find(c => c.id === ev.classId);
            const className = classObj ? classObj.name : ev.classId;
            
            const item = document.createElement('div');
            item.className = 'calendar-event-item';
            item.innerHTML = `
                <h4>Absensi Wali Kelas</h4>
                <p>Kelas: ${className}</p>
                <p>Jumlah Siswa: ${ev.records.length} Diabsen</p>
            `;
            listEl.appendChild(item);
        });

        // Render Mapel
        mapelEvents.forEach(ev => {
            const classObj = window.Calendar.allClasses.find(c => c.id === ev.classId);
            const className = classObj ? classObj.name : ev.classId;
            
            const item = document.createElement('div');
            item.className = 'calendar-event-item';
            item.style.borderLeftColor = 'var(--color-indigo)'; // differentiate color
            item.innerHTML = `
                <h4>Absensi Mata Pelajaran</h4>
                <p>Kelas: ${className} | Jam ke-${ev.jamKe}</p>
                <p>Jumlah Siswa: ${ev.records.length} Diabsen</p>
            `;
            listEl.appendChild(item);
        });
    }
};
